name: Versioning

on:
  push:
    branches:
      - main  # Disparar apenas no branch principal
    paths:
      - 'version.txt'  # SÃ³ executa se o version.txt for modificado

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
          echo "NEW_TAG=v$(cat version.txt)" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag $NEW_TAG
          git push origin $NEW_TAG